'use client';
import { useState,useEffect } from 'react';
import { ArrowUpRight, Clock3, Sparkles, ArrowRight } from 'lucide-react';
import briefings from '@/lib/data/briefings.json';
export default function Home(){
 const [lang,setLang]=useState<'zh'|'en'>('zh');
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('lang')==='en')setLang('en')},[]);
 function changeLanguage(v:'zh'|'en'){setLang(v);const u=new URL(window.location.href);u.searchParams.set('lang',v);window.history.replaceState(null,'',u);}
 return <main className="shell" lang={lang==='zh'?'zh-CN':'en'}><header className="masthead"><div className="logo-crop"><img src="/media/logo.png" alt="GCGF — Green Connect Green Future"/></div><div className="edition">AUSTRALIAN CLEAN ENERGY SUMMIT <span>2026</span></div><h1>{lang==='zh'?'澳大利亚清洁能源简报':'Australian Clean Energy Briefings'}</h1><p>{lang==='zh'?'会议观点 · 行业洞察 · 原始资料':'Conversations · Industry perspectives · Original sources'}</p><div className="header-bottom"><span>28–29 JUL 2026 <i/>11 {lang==='zh'?'份会议资料':'briefings'}</span><div className="language" aria-label="Language"><button aria-pressed={lang==='zh'} onClick={()=>changeLanguage('zh')}>中文</button><button aria-pressed={lang==='en'} onClick={()=>changeLanguage('en')}>EN</button></div></div></header>
 <div className="section-title"><h2>{lang==='zh'?'会议 Highlights':'Conference highlights'}</h2><span>01 — 11</span></div><div className="cards">{briefings.map(b=>{const c=b.content[lang];return <a className="brief-card" key={b.id} href={`/briefing/${b.slug}?lang=${lang}`}><div className="card-top"><span className="tag">{lang==='zh'?({'Community':'社区共建','Climate security':'气候安全','Data centers':'数据中心','Investment':'能源投资','Environment':'环境审批','Storage':'储能与电网','State policy':'州级政策','Market design':'市场机制','Climate risk':'气候韧性'} as Record<string,string>)[b.tags[0]]||b.tags[0]:b.tags[0]}</span><ArrowUpRight size={20}/></div><div className="card-meta">{b.date}<span><Clock3 size={13}/>{b.duration}</span></div><h3>{c.title}</h3><div className="card-highlights"><div className="eyebrow"><Sparkles size={14}/>{c.highlights.length?'HIGHLIGHTS':lang==='zh'?'内容摘要':'OVERVIEW'}</div>{c.highlights.length?<ul>{c.highlights.slice(0,2).map(h=><li key={h.time}>{h.title}</li>)}</ul>:<p>{c.brief.split('\n')[0]}</p>}</div><div className="card-bottom"><span>{lang==='zh'?'查看完整资料':'Read briefing'}{c.highlights.length>0&&<small> · {c.highlights.length} Highlights</small>}</span><ArrowRight size={17}/></div></a>})}</div><footer>GCGF <span>GREEN CONNECT · GREEN FUTURE</span><small>{lang==='zh'?'更新于 2026 年 9 月 10 日':'Updated September 10, 2026'}</small></footer></main>
}
